version: '1.0'
services:
  postgres:
    image: postgres:15
    env_file: .env
    container_name: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file: .env
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "8082:80"
    depends_on:
      - postgres

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    container_name: server
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
      - DB_NAME
      - FIREBASE_SERVICE_ACCOUNT
    ports:
      - "3333:3000"
    depends_on:
      - postgres

volumes:
  pgdata:
